# Public data
application_name: 'Anfora'
server_description: ''

# http config
scheme: 'https'
domain: 'anfora.test'

# Positition

root_path: '/home/yabir/killMe/anfora'

# Storage

media_folder: '/home/yabir/killMe/uploads'
thumb_folder: 'small'
image_folder: 'max_resolution'
icons_folder: 'icons'

# Uri salt

salt_code: 'whySoSalty?'